var tokens= new Meteor.Collection('key_tokens')

//tokens.insert({key: 'asdasd-cnz'})

//use the mongo id as the token

KeyToken={
  validateToken:function(token, key){
    if (!token){
      throw new Meteor.Error(403,'invalid token')
    }
    var token=tokens.findOne({
      key: key,
      _id: token
    })
    if (!token){
      throw new Meteor.Error(403,'invalid token')
    }

    //consume token
    tokens.remove({_id: token._id});

    return true;

  },

  createToken: function(key){
    if (!key)
      throw new Error('key not valid ('+key+')')

    return tokens.insert({
      key: key,
      //the token will be generated by mongo in the _id
    })
  }
};


